version: "2"
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/myapp
      - /myapp/tmp
    env_file:
      - .env

  db:
    image: mysql/mysql-server:latest
    env_file:
      - .env
    ports:
      - 55551:3306
    expose:
      - 55551
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - sql_data:/var/lib/mysql

  redis:
    image: redis:4.0-alpine

volumes:
  sql_data:
